import assert from "node:assert/strict";
import { dedupeCalendarTitles, duplicateOverlaps, normalizedCalendarTitle } from "./calendar-duplicates";
import { activeCalendarPriority, calendarLinksOf, calendarNamesOf, calendarPriorityOrderOf, detectCalendarLink, outrankCalendarPriority, reorderCalendarPriority, showDuplicateEventsOf } from "./calendar-priority";
import type { TimelineItem } from "./types";

const start = new Date(2026, 9, 1, 12).getTime();
const learn: TimelineItem = { id: "learn", kind: "event", title: " CS 246   Assignment 1 ", startUTC: start, endUTC: start + 3600000, allDay: false, importSource: "learn", description: "Full assignment details" };
const portal: TimelineItem = { ...learn, id: "portal", title: "cs 246 assignment 1", importSource: "portal", description: undefined };
const nextDay: TimelineItem = { ...portal, id: "tomorrow", startUTC: new Date(2026, 9, 2, 12).getTime() };
assert.equal(normalizedCalendarTitle("Ａssignment\u00a0  1"), "assignment 1");
assert.deepEqual(dedupeCalendarTitles([portal, learn], ["learn", "portal"]), [learn]);
assert.deepEqual(dedupeCalendarTitles([portal, learn], ["portal", "learn"]), [portal]);
assert.deepEqual(dedupeCalendarTitles([portal, learn], ["learn", "portal"], true), [portal, learn]);
assert.deepEqual(dedupeCalendarTitles([learn, nextDay], ["learn", "portal"]), [learn, nextDay]);
assert.deepEqual(dedupeCalendarTitles([portal], ["learn", "portal"]), [portal], "no hiding without preferred match");
const googlePortal: TimelineItem = { ...portal, id: "gcal", kind: "gcal_event", importSource: undefined, google: { calendarName: "UWaterloo Portal" } };
assert.deepEqual(dedupeCalendarTitles([googlePortal, learn], ["learn", "portal", "google"]).map((item) => item.id), ["learn"]);
assert.deepEqual(dedupeCalendarTitles([googlePortal, portal], ["google", "portal"]).map((item) => item.id), ["gcal"]);
const googleLearn: TimelineItem = { ...learn, id: "google-learn", kind: "gcal_event", importSource: undefined, google: { calendarName: "LEARN calendar" } };
assert.deepEqual(dedupeCalendarTitles([googlePortal, googleLearn], ["portal", "learn"]).map((item) => item.id), ["google-learn"]);
assert.deepEqual(dedupeCalendarTitles([googlePortal, googleLearn], ["google"]).map((item) => item.id), ["google-learn"]);
assert.deepEqual(dedupeCalendarTitles([googlePortal], ["google"]).map((item) => item.id), ["gcal"]);
assert.deepEqual(dedupeCalendarTitles([googlePortal, googleLearn, learn], ["learn", "google"]).map((item) => item.id), ["learn"]);
const task = { ...portal, id: "task", kind: "task" as const };
const manual = { ...portal, id: "manual", importSource: undefined };
const other = { ...portal, id: "other", importSource: "other" as const };
const draft = { ...portal, id: "draft", editorDraft: true };
const pending = { ...portal, id: "pending", pendingApproval: true };
assert.deepEqual(dedupeCalendarTitles([learn, task, manual, other, draft, pending], ["learn", "portal"]), [learn, task, manual, other, draft, pending]);
assert.deepEqual(dedupeCalendarTitles([learn, { ...learn, id: "copy" }, portal], ["learn", "portal"]).map((item) => item.id), ["learn"], "identical copies from one feed show once");
assert.deepEqual(dedupeCalendarTitles([portal, { ...portal, id: "copy" }], ["learn", "portal"]).map((item) => item.id), ["portal"], "same-source copies collapse even when that source wins");
assert.deepEqual(dedupeCalendarTitles([portal, { ...portal, id: "copy" }], ["learn", "portal"], true).map((item) => item.id), ["portal", "copy"], "show-duplicates setting still reveals them");
assert.deepEqual(dedupeCalendarTitles([portal, { ...portal, id: "room", location: "MC 2038" }], ["portal"]).map((item) => item.id), ["portal", "room"], "same time in another room is a different event");
assert.deepEqual(dedupeCalendarTitles([manual, { ...manual, id: "manual-copy" }], ["portal"]).map((item) => item.id), ["manual", "manual-copy"], "hand-made events are never hidden");
assert.equal(portal.description, undefined, "records are not overwritten");
const googlePersonal: TimelineItem = { ...learn, id: "personal", kind: "gcal_event", importSource: undefined, google: { calendarName: "Personal" } };
assert.deepEqual(dedupeCalendarTitles([googlePersonal, learn, portal], ["google", "learn", "portal"]).map((item) => item.id), ["personal"]);
assert.deepEqual(dedupeCalendarTitles([googlePersonal, learn], ["learn", "portal", "google"]).map((item) => item.id), ["learn"]);
assert.deepEqual(dedupeCalendarTitles([googlePersonal, learn], ["learn", "portal"]).map((item) => item.id), ["personal", "learn"], "google stays visible until it is in the priority list");
const formStart = new Date(2026, 8, 29, 11, 30).getTime();
const form = { ...learn, id: "form", title: "Video Release Form", startUTC: formStart, endUTC: formStart };
const formDue = { ...portal, id: "form-due", title: "Video Release Form - Due", startUTC: formStart, endUTC: formStart };
assert.deepEqual(dedupeCalendarTitles([formDue, form], ["learn", "portal"]).map((item) => item.id), ["form"]);
assert.deepEqual(dedupeCalendarTitles([formDue, form], ["portal", "learn"]).map((item) => item.id), ["form-due"]);
const formLater = { ...form, id: "form-later", endUTC: formStart + 60000 };
assert.deepEqual(dedupeCalendarTitles([formDue, formLater], ["learn", "portal"]).map((item) => item.id), ["form-due", "form-later"]);
const googleForm = { ...form, id: "g-form", kind: "gcal_event" as const, importSource: undefined, google: { calendarName: "LEARN" } };
const googleFormDue = { ...formDue, id: "g-due", kind: "gcal_event" as const, importSource: undefined, google: { calendarName: "UWaterloo Portal" } };
assert.deepEqual(dedupeCalendarTitles([googleFormDue, googleForm], ["google"]).map((item) => item.id), ["g-form"]);
const googleCopy: TimelineItem = { ...learn, id: "g-copy", kind: "gcal_event", importSource: undefined, google: { calendarName: "Personal" } };
assert.deepEqual(duplicateOverlaps([learn, portal, googleCopy], ["learn", "portal", "google"]), [
  { a: "learn", b: "portal", count: 1 },
  { a: "learn", b: "google", count: 1 },
  { a: "portal", b: "google", count: 1 },
]);
assert.deepEqual(duplicateOverlaps([learn, portal], ["portal", "learn"]), [{ a: "portal", b: "learn", count: 1 }], "pairs follow priority order");
assert.deepEqual(duplicateOverlaps([learn, nextDay], ["learn", "portal"]), [{ a: "learn", b: "portal", count: 0 }], "different days share nothing");
assert.deepEqual(duplicateOverlaps([learn, { ...learn, id: "copy" }, portal], ["learn", "portal"]), [{ a: "learn", b: "portal", count: 1 }], "two copies in one feed count once");
assert.deepEqual(duplicateOverlaps([learn, { ...portal, id: "nested", title: "CS 246 Assignment 1 due" }], ["learn", "portal"]), [{ a: "learn", b: "portal", count: 1 }], "a nested title at the same times is a copy");
assert.deepEqual(duplicateOverlaps([learn, { ...portal, kind: "task" }, { ...portal, id: "d", editorDraft: true }, { ...portal, id: "p", pendingApproval: true }], ["learn", "portal"]), [{ a: "learn", b: "portal", count: 0 }], "tasks, drafts and pending changes never compete");
assert.deepEqual(duplicateOverlaps([learn, portal], ["learn"]), [], "one source has no pairs");
assert.deepEqual(outrankCalendarPriority(["learn", "portal", "google"], "google", "learn"), ["google", "learn", "portal"]);
assert.deepEqual(outrankCalendarPriority(["learn", "portal", "google"], "google", "portal"), ["learn", "google", "portal"]);
const settled: ("learn" | "portal")[] = ["learn", "portal"];
assert.equal(outrankCalendarPriority(settled, "learn", "portal"), settled, "an order where it already wins comes back unchanged");
assert.equal(outrankCalendarPriority(settled, "google", "learn"), settled, "a source outside the order changes nothing");
console.log("Title normalization, day boundaries, LEARN/Portal/Google priority, show-both, and record preservation passed.");

const order = calendarPriorityOrderOf(["learn", "portal"]);
assert.deepEqual(calendarPriorityOrderOf(undefined), []);
assert.deepEqual(calendarPriorityOrderOf(undefined, "portal"), ["portal", "learn"]);
assert.deepEqual(calendarPriorityOrderOf(["portal", "learn"]), ["portal", "learn"]);
assert.deepEqual(calendarPriorityOrderOf(["learn", "learn"]), []);
assert.deepEqual(calendarPriorityOrderOf(["google", "learn", "portal"]), ["google", "learn", "portal"]);
assert.deepEqual(calendarPriorityOrderOf(["portal"]), ["portal"]);
assert.equal(showDuplicateEventsOf(undefined, "show_all"), true);
assert.equal(showDuplicateEventsOf(false, "show_all"), false);
const dragged = reorderCalendarPriority(order, "portal", "learn");
assert.deepEqual(dragged, ["portal", "learn"]);
assert.deepEqual(dedupeCalendarTitles([learn, portal], dragged), [portal], "dragging Portal to the top changes the duplicate winner");
assert.deepEqual(reorderCalendarPriority(dragged, "learn", "portal"), ["learn", "portal"]);
assert.equal(reorderCalendarPriority(order, "learn", "learn"), order);
assert.equal(reorderCalendarPriority(order, "unknown", "learn"), order);
assert.deepEqual(dedupeCalendarTitles([learn, portal], dragged, true), [learn, portal], "show-both retains the chosen order");

assert.deepEqual(calendarPriorityOrderOf([]), []);
assert.deepEqual(dedupeCalendarTitles([learn, portal, manual], ["portal"]), [portal, manual]);
assert.deepEqual(dedupeCalendarTitles([learn, portal, manual], [], true), [manual], "show both does not restore removed calendars");
assert.deepEqual(reorderCalendarPriority(["portal"], "portal", "learn"), ["portal"]);

assert.deepEqual(calendarNamesOf({ learn: "  My courses  ", portal: "", other: "ignored" }), { learn: "My courses" });
assert.deepEqual(calendarNamesOf({ learn: "x".repeat(81), portal: 5 }), {});
assert.deepEqual(calendarLinksOf({ learn: " https://learn.example/a.ics ", portal: "javascript:alert(1)", google: "https://nope.example", other: "https://example.com/a.ics" }), { learn: "https://learn.example/a.ics", other: "https://example.com/a.ics" });
assert.equal(detectCalendarLink("https://learn.uwaterloo.ca/d2l/le/calendar/feed.ics"), "learn");
assert.equal(detectCalendarLink("webcal://portal.uwaterloo.ca/export.ics"), "portal");
assert.equal(detectCalendarLink("https://example.com/calendar.ics"), "other");
assert.deepEqual(activeCalendarPriority(["portal", "learn"], { learn: "https://learn.example/a.ics" }, false), []);
assert.deepEqual(activeCalendarPriority(["portal", "learn"], { learn: "https://learn.example/a.ics" }, false, { learn: true }), ["learn"]);
assert.deepEqual(activeCalendarPriority(["learn"], { learn: "https://learn.example/a.ics", portal: "webcal://portal.example/b.ics" }, true, { learn: true }), ["learn", "google"]);
assert.deepEqual(activeCalendarPriority(["learn"], { learn: "https://learn.example/a.ics", portal: "webcal://portal.example/b.ics" }, true, { learn: true, portal: true }), ["learn", "portal", "google"]);
assert.deepEqual(activeCalendarPriority(["google"], { learn: "https://learn.example/a.ics", portal: "webcal://portal.example/b.ics" }, true, { learn: true, portal: true }), ["learn", "portal", "google"]);
assert.deepEqual(activeCalendarPriority(["google", "portal"], { portal: "webcal://portal.example/b.ics" }, true, { portal: true }), ["google", "portal"]);
assert.deepEqual(activeCalendarPriority(["google", "learn"], {}, null), ["google"]);
assert.deepEqual(activeCalendarPriority([], {}, false), []);
