import assert from "node:assert/strict";
import { calendarItemVisible, externalCalendarsOf } from "./external-calendars";
import type { CalendarItemDoc } from "./types";
const learn: CalendarItemDoc = { id: "a", title: "Assignment", createdAt: 0, updatedAt: 0, calendar: { kind: "event", startUTC: 0, endUTC: 1, allDay: false, importSource: "learn" } };
const portal: CalendarItemDoc = { ...learn, id: "b", calendar: { ...learn.calendar, importSource: "portal" } };
const manual: CalendarItemDoc = { ...learn, id: "c", calendar: { ...learn.calendar, importSource: undefined } };
const filter = { events: false, tasks: false, google: false, mutedGoogleIds: [], hiddenIds: [] };
assert.equal(calendarItemVisible(learn, filter), true, "imports are independent of WatAgent/Google visibility");
assert.equal(calendarItemVisible(manual, filter), false);
assert.equal(calendarItemVisible(learn, { ...filter, mutedGoogleIds: ["ics:learn"] }), false);
assert.equal(calendarItemVisible(portal, { ...filter, mutedGoogleIds: ["ics:learn"] }), true);
assert.equal(calendarItemVisible(learn, { ...filter, hiddenIds: ["ics:learn"] }), false);
assert.deepEqual(externalCalendarsOf([learn, portal, manual], { learn: "Courses" }, ["portal", "learn"]).map((row) => row.name), ["Portal", "Courses"]);
assert.deepEqual(externalCalendarsOf([learn, portal], {}, []), [], "removed calendars stay absent");
assert.deepEqual(externalCalendarsOf([], {}, ["learn", "portal"]), [], "no phantom calendars");
console.log("External calendar listing, names, priority, independent visibility, and removal checks passed.");
