import assert from "node:assert/strict";
import { calendarItemVisible, externalCalendarsOf } from "./external-calendars";
import type { CalendarItemDoc } from "./types";
const learn: CalendarItemDoc = { id: "a", title: "Assignment", createdAt: 0, updatedAt: 0, calendar: { kind: "event", startUTC: 0, endUTC: 1, allDay: false, importSource: "learn" } };
const portal: CalendarItemDoc = { ...learn, id: "b", calendar: { ...learn.calendar, importSource: "portal" } };
const manual: CalendarItemDoc = { ...learn, id: "c", calendar: { ...learn.calendar, importSource: undefined } };
const filter = { events: false, tasks: false, google: false, mutedGoogleIds: [], hiddenIds: [] };
assert.equal(calendarItemVisible(learn, filter), true, "imports are independent of WatAgent/Google visibility");
assert.equal(calendarItemVisible(manual, filter), false);
assert.equal(calendarItemVisible(learn, { ...filter, mutedGoogleIds: ["ics:learn"] }), false);
assert.equal(calendarItemVisible(portal, { ...filter, mutedGoogleIds: ["ics:learn"] }), true);
assert.equal(calendarItemVisible(learn, { ...filter, hiddenIds: ["ics:learn"] }), false);
const links = { learn: "https://learn.example/a.ics", portal: "webcal://portal.example/b.ics" };
assert.deepEqual(externalCalendarsOf([learn, portal, manual], { learn: "Courses" }, ["portal", "learn"], links).map((row) => row.name), ["Portal", "Courses"]);
assert.deepEqual(externalCalendarsOf([learn, portal], {}, [], links), [], "removed calendars stay absent");
assert.deepEqual(externalCalendarsOf([], {}, ["learn", "portal"]), [], "no phantom calendars");
assert.deepEqual(externalCalendarsOf([learn], {}, ["learn"], {}), [], "events without a saved link stay off the list");
assert.deepEqual(externalCalendarsOf([], { learn: "Courses" }, ["learn"], { learn: links.learn }), [], "a saved link stays off the list until events are imported");
assert.deepEqual(externalCalendarsOf([learn], { learn: "Courses" }, ["learn"], links).map((row) => row.name), ["Courses"]);
const groupsOff = { watagent: true, external: false, other: true, smartTags: true, hidden: false };
assert.equal(calendarItemVisible(learn, { ...filter, groups: groupsOff }), false, "hiding the external group keeps each calendar's own check");
assert.equal(calendarItemVisible(manual, { ...filter, events: true, groups: { ...groupsOff, watagent: false, external: true } }), false);
assert.equal(calendarItemVisible(learn, { ...filter, hiddenIds: ["ics:learn"], groups: { ...groupsOff, external: true } }), false);
assert.equal(calendarItemVisible(learn, { ...filter, hiddenIds: ["ics:learn"], groups: { ...groupsOff, external: true, hidden: true } }), true, "the hidden header shows those calendars without clearing the list");
console.log("External calendar listing, names, priority, independent visibility, and removal checks passed.");
