import assert from "node:assert/strict";
import { calendarItemVisible, externalCalendarsOf } from "./external-calendars";
import { ALL_SOURCES, isCalendarReadOnly, setCalendarReadOnly } from "./preferences";
import type { CalendarItemDoc } from "./types";
const learn: CalendarItemDoc = { id: "a", title: "Assignment", createdAt: 0, updatedAt: 0, calendar: { kind: "event", startUTC: 0, endUTC: 1, allDay: false, importSource: "learn" } };
const portal: CalendarItemDoc = { ...learn, id: "b", calendar: { ...learn.calendar, importSource: "portal" } };
const manual: CalendarItemDoc = { ...learn, id: "c", calendar: { ...learn.calendar, importSource: undefined } };
const filter = { ...ALL_SOURCES, events: false, tasks: false, google: false };
assert.equal(calendarItemVisible(learn, filter), true, "imports are independent of WatAgent/Google visibility");
assert.equal(calendarItemVisible(manual, filter), false);
assert.equal(calendarItemVisible(learn, { ...filter, mutedGoogleIds: ["ics:learn"] }), false);
assert.equal(calendarItemVisible(portal, { ...filter, mutedGoogleIds: ["ics:learn"] }), true);
assert.equal(calendarItemVisible(learn, { ...filter, hiddenIds: ["ics:learn"] }), false);
const learnUrl = "https://learn.example/a.ics";
const imported = [{ id: "portal" as const, name: "Portal", url: "webcal://portal.example/b.ics" }, { id: "learn" as const, name: "Courses", url: learnUrl }];
assert.deepEqual(externalCalendarsOf([learn, portal, manual], imported).map((row) => row.name), ["Portal", "Courses"], "saved order and names");
assert.deepEqual(externalCalendarsOf([], imported).map((row) => row.id), ["ics:portal", "ics:learn"], "a saved link shows before its first events arrive");
assert.deepEqual(externalCalendarsOf([learn], []).map((row) => [row.id, row.name]), [["ics:learn", "Imported calendar"]], "events without a saved link still get a row");
assert.deepEqual(externalCalendarsOf([], []), [], "no phantom calendars");
const school = { id: "merge-0b5c2f8e-3a4d-4e1f-9c2b-7d6e5f4a3b2c", name: "School", members: ["ics:learn", "ics:portal"] };
assert.equal(calendarItemVisible(learn, { ...filter, mutedGoogleIds: ["ics:learn"] }, [school]), true, "a member follows its merged calendar");
assert.equal(calendarItemVisible(learn, { ...filter, mutedGoogleIds: [school.id] }, [school]), false);
const groupsOff = { watagent: true, external: false, other: true, smartTags: true, hidden: false };
assert.equal(calendarItemVisible(learn, { ...filter, groups: groupsOff }), false, "hiding the external group keeps each calendar's own check");
assert.equal(calendarItemVisible(manual, { ...filter, events: true, groups: { ...groupsOff, watagent: false, external: true } }), false);
assert.equal(calendarItemVisible(learn, { ...filter, hiddenIds: ["ics:learn"], groups: { ...groupsOff, external: true } }), false);
assert.equal(calendarItemVisible(learn, { ...filter, hiddenIds: ["ics:learn"], groups: { ...groupsOff, external: true, hidden: true } }), true, "the hidden header shows those calendars without clearing the list");
assert.equal(isCalendarReadOnly(ALL_SOURCES, "ics:learn"), true, "imported calendars are always read only");
assert.equal(isCalendarReadOnly(ALL_SOURCES, "ics:feed-0b5c2f8e-3a4d-4e1f-9c2b-7d6e5f4a3b2c"), true);
assert.equal(isCalendarReadOnly(setCalendarReadOnly(ALL_SOURCES, "ics:learn", false), "ics:learn"), true, "and can't be unlocked");
assert.equal(isCalendarReadOnly(ALL_SOURCES, "merge-0b5c2f8e-3a4d-4e1f-9c2b-7d6e5f4a3b2c"), true);
assert.equal(isCalendarReadOnly(ALL_SOURCES, "events"), false);
console.log("External calendar listing, names, merged visibility, independent visibility, and removal checks passed.");
