import assert from "node:assert/strict";
import { configureMerge } from "./merge-function";
const feeds = ["ics:a", "ics:b", "ics:c", "ics:d"];
const nameOf = (id: string) => id;
const output = { id: "merge-new", name: "School", members: feeds.slice(0, 2) };
const created = configureMerge(output, feeds, [], [], nameOf);
assert.deepEqual(created.merged, [output]);
assert.equal(created.created.length, 1);
assert.deepEqual(created.drafts, []);
const reordered = configureMerge({ ...output, name: "Courses", members: [feeds[1], feeds[0]] }, feeds, created.merged, [], nameOf);
assert.deepEqual(reordered.merged[0], { ...output, name: "Courses", members: [feeds[1], feeds[0]] });
assert.equal(reordered.created.length, 0);
const moved = configureMerge({ id: "merge-second", name: "Second", members: [feeds[0], feeds[2]] }, feeds, created.merged, [], nameOf);
assert.deepEqual(moved.drafts[0].members, [feeds[1]], "the previous output retains its remaining source as a draft");
assert.deepEqual(moved.merged[0].members, [feeds[0], feeds[2]]);
assert.deepEqual(created.merged, [output], "configuration does not mutate previous data");
assert.throws(() => configureMerge({ ...output, members: [feeds[0], feeds[0]] }, feeds, [], [], nameOf));
assert.throws(() => configureMerge({ ...output, members: [feeds[0], "missing"] }, feeds, [], [], nameOf));
console.log("Merge function checks passed.");
